### ISSUE TITLE
Any reference paper for this implementation?

### ISSUE THREAD

**Issue by EstherBear** [RosettaCommons/trRosetta2#2]
Do you have reference paper for this implementation? I want to know why it work and how it work. Thanks!!!

**Comment by gjoni** [comment]
We have submitted a paper to journal but it has not been published yet. This is the reference for now:

I Anishchenko, M Baek, H Park, J Dauparas, N Hiranuma, S Mansoor, I Humphrey, D Baker. Protein structure prediction guided by predicted inter-residue geometries. In: [CASP14 Abstract Book, 2020](https://predictioncenter.org/casp14/doc/CASP14_Abstracts.pdf)
